site_name: FastServe
site_description: 'Machine Learning Serving focused on GenAI & LLMs with simplicity as the top priority.'
site_author: Aniket Maurya
copyright: 'Copyright &copy; 2024 Aniket Maurya'

banner_url: https://ik.imagekit.io/gradsflow/logo/v2/gf-cover-hd_N3naW2FHA.png?updatedAt=1710282045836
repo_url: https://github.com/gradsflow/fastserve-ai/
repo_name: aniketmaurya/fastserve

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

  logo: https://raw.githubusercontent.com/aniketmaurya/blog/main/assets/blog.png
  favicon: https://raw.githubusercontent.com/aniketmaurya/blog/main/assets/favicon.ico
  features:
    - search.suggest
    - search.highlight

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - git-revision-date-localized
  - search
#  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false

extra:
  homepage: https://github.com/gradsflow/fastserve-ai
  analytics:
    provider: google
    property: G-B8FPDYGVPR

nav:
  - Introduction: 'index.md'
  - Image GenAI: fastserve/models/image_gen.md
  - LLMs:
      - vLLM: fastserve/models/llms/vllm.md
      - Local LLMs: fastserve/models/llms/local_llms.md
      - HF LLMs: fastserve/models/llms/hf.md
  - Containerization: fastserve/containerization.md
  - Release Notes: 'CHANGELOG.md'
